### ISSUE TITLE
Domain dead

### ISSUE THREAD

**Issue by sfcgeorge** [camping/camping.io#4]
camping.io is dead. As the camping.io site is a gh-pages one, I think the CNAME file could just be deleted then it will be available again at camping.github.io/camping.io

**Comment by sethkrasnianski** [comment]
camping.io seems to be a phishing website that serves both google and apple phishing pages. 😢

**Comment by DaveEveritt** [comment]
Bit sad, but the domain hasn't been renewed as the project is basically archived. Best we could do for now is point to http://whywentcamping.judofyr.net/ which is still okay.

**Comment by sfcgeorge** [comment]
That's not necessary, the current website still works it's only the domain name that expired. So you just need to change `http://camping.io` to `http://camping.github.io/camping.io` [in the project description, which I don't think can be pull-requested so an owner will have to change it]

**Comment by DaveEveritt** [comment]
I can't do that, so notified those who (I think) can.

**Comment by Bluebie** [comment]
Done
